### ISSUE TITLE
Server Test Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by bkesecker** [EdenServer/eden-web#81]
To build on live, had to change package.json, lines:
```
    "clean": "rimraf build",
    "build:client": "cd client && npm run build && move build ../build/public",
```
but
```
Error while loading items Error: getaddrinfo ENOTFOUND 54.39.106.219
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '54.39.106.219\r',
  fatal: true
}
Error while loading item keys Error: getaddrinfo ENOTFOUND 54.39.106.219
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '54.39.106.219\r',
  fatal: true
}
```
Attempting to load from http://54.39.106.219:8080/ results in a blank page with the following errors
```
2.439913bc.chunk.js:1 Uncaught SyntaxError: Unexpected token '<'
main.4074338e.chunk.js:1 Uncaught SyntaxError: Unexpected token '<'
```

**Comment by bkesecker** [comment]
Was able to resolve this error be removing \r from .env file
```
Error while loading items Error: getaddrinfo ENOTFOUND 54.39.106.219
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '54.39.106.219\r',
  fatal: true
}
```
but browser Syntax error persists.

**Comment by bkesecker** [comment]
This appears to be resolved in latest master branch.
